apiVersion: v1
kind: Secret
metadata:
  name: {{ template "clair.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "clair.fullname" . }}
type: Opaque
data:
  postgresql-ca-cert: {{ default "" .Values.config.postgresCaCert | b64enc | quote }}
  config.yaml: |-
{{ include (print .Template.BasePath "/_config.yaml.tpl") . | b64enc | indent 4 }}